auth_type: basic
board:
  id: 378
  name: FUL board
  type: scrum
epic:
  name: customfield_10011
  link: customfield_10014
installation: Cloud
issue:
  fields:
    custom:
      - name: Frequency and Ability to Replicate
        key: customfield_10590
        schema:
          datatype: array
          items: option
      - name: "HubSpot ticket count (Hub ID: 20864687)"
        key: customfield_10077
        schema:
          datatype: number
      - name: Idea archived
        key: customfield_10110
        schema:
          datatype: option
      - name: Idea archived by
        key: customfield_10111
        schema:
          datatype: array
          items: user
      - name: Idea archived on
        key: customfield_10112
        schema:
          datatype: datetime
      - name: Atlassian project
        key: customfield_10113
        schema:
          datatype: string
      - name: Atlassian project status
        key: customfield_10114
        schema:
          datatype: string
      - name: Device info
        key: customfield_10588
        schema:
          datatype: string
      - name: Couri Account Email
        key: customfield_10589
        schema:
          datatype: string
      - name: Release Notes Title
        key: customfield_10623
        schema:
          datatype: string
      - name: Release Notes
        key: customfield_10624
        schema:
          datatype: string
      - name: Company
        key: customfield_10341
        schema:
          datatype: string
      - name: URL
        key: customfield_10342
        schema:
          datatype: string
      - name: Browser/App info
        key: customfield_10587
        schema:
          datatype: string
      - name: T-Shirt Size
        key: customfield_10176
        schema:
          datatype: option
      - name: Release Notes
        key: customfield_10210
        schema:
          datatype: string
      - name: Release Notes Title
        key: customfield_10209
        schema:
          datatype: string
      - name: Vulnerability
        key: customfield_10040
        schema:
          datatype: any
      - name: Sentiment
        key: customfield_10041
        schema:
          datatype: array
          items: sd-sentiment
      - name: Goals
        key: customfield_10043
        schema:
          datatype: array
          items: Goals
      - name: Clockwork Timer
        key: customfield_10044
        schema:
          datatype: string
      - name: Design
        key: customfield_10039
        schema:
          datatype: array
          items: design.field.name
      - name: Time to resolution
        key: customfield_10150
        schema:
          datatype: sd-servicelevelagreement
      - name: Total forms
        key: customfield_10030
        schema:
          datatype: number
      - name: Time to first response
        key: customfield_10151
        schema:
          datatype: sd-servicelevelagreement
      - name: Time to close after resolution
        key: customfield_10152
        schema:
          datatype: sd-servicelevelagreement
      - name: Product categorization
        key: customfield_10153
        schema:
          datatype: option-with-child
      - name: Project overview key
        key: customfield_10033
        schema:
          datatype: string
      - name: Operational categorization
        key: customfield_10154
        schema:
          datatype: option-with-child
      - name: Project overview status
        key: customfield_10034
        schema:
          datatype: string
      - name: Browser/App info
        key: customfield_10551
        schema:
          datatype: string
      - name: Story Points
        key: customfield_10035
        schema:
          datatype: number
      - name: Device info
        key: customfield_10552
        schema:
          datatype: string
      - name: Planly Account Email
        key: customfield_10553
        schema:
          datatype: string
      - name: Category
        key: customfield_10036
        schema:
          datatype: option
      - name: Frequency and Ability to Replicate
        key: customfield_10554
        schema:
          datatype: array
          items: option
      - name: Locked forms
        key: customfield_10027
        schema:
          datatype: number
      - name: Severity
        key: customfield_10148
        schema:
          datatype: option
      - name: Affected hardware
        key: customfield_10149
        schema:
          datatype: string
      - name: Open forms
        key: customfield_10028
        schema:
          datatype: number
      - name: Submitted forms
        key: customfield_10029
        schema:
          datatype: number
      - name: Time to done
        key: customfield_10308
        schema:
          datatype: sd-servicelevelagreement
      - name: Project start
        key: customfield_10380
        schema:
          datatype: string
      - name: State
        key: customfield_10381
        schema:
          datatype: option
      - name: Satisfaction date
        key: customfield_10140
        schema:
          datatype: datetime
      - name: Impact
        key: customfield_10382
        schema:
          datatype: number
      - name: Request language
        key: customfield_10141
        schema:
          datatype: sd-request-lang
      - name: Design file
        key: customfield_10383
        schema:
          datatype: string
      - name: Sprint
        key: customfield_10020
        schema:
          datatype: array
          items: json
      - name: Flagged
        key: customfield_10021
        schema:
          datatype: array
          items: option
      - name: Impact (migrated)
        key: customfield_10780
        schema:
          datatype: option
      - name: Theme
        key: customfield_10384
        schema:
          datatype: array
          items: option
      - name: Urgency
        key: customfield_10142
        schema:
          datatype: option
      - name: Customer segments
        key: customfield_10385
        schema:
          datatype: array
          items: option
      - name: Change reason (migrated)
        key: customfield_10781
        schema:
          datatype: option
      - name: Target start
        key: customfield_10022
        schema:
          datatype: date
      - name: Pending reason
        key: customfield_10143
        schema:
          datatype: option
      - name: Target end
        key: customfield_10023
        schema:
          datatype: date
      - name: Actual end (migrated)
        key: customfield_10782
        schema:
          datatype: datetime
      - name: Designs ready
        key: customfield_10386
        schema:
          datatype: number
      - name: Affected services
        key: customfield_10144
        schema:
          datatype: array
          items: service-entity-field
      - name: Solutions Company
        key: customfield_10387
        schema:
          datatype: option
      - name: Related Slack message URL
        key: customfield_10783
        schema:
          datatype: string
      - name: "[CHART] Date of First Response"
        key: customfield_10024
        schema:
          datatype: datetime
      - name: Approver groups
        key: customfield_10145
        schema:
          datatype: array
          items: group
      - name: "[CHART] Time in Status"
        key: customfield_10025
        schema:
          datatype: any
      - name: Approver groups (migrated)
        key: customfield_10784
        schema:
          datatype: array
          items: group
      - name: Major incident
        key: customfield_10146
        schema:
          datatype: string
      - name: Actual Behaviour
        key: customfield_10785
        schema:
          datatype: string
      - name: Responders
        key: customfield_10147
        schema:
          datatype: array
          items: string
      - name: Documents
        key: customfield_10379
        schema:
          datatype: string
      - name: Impact Assessment
        key: customfield_10775
        schema:
          datatype: string
      - name: Story point estimate
        key: customfield_10016
        schema:
          datatype: number
      - name: Approvals
        key: customfield_10137
        schema:
          datatype: sd-approvals
      - name: Actual start (migrated)
        key: customfield_10776
        schema:
          datatype: datetime
      - name: Issue color
        key: customfield_10017
        schema:
          datatype: string
      - name: Request participants
        key: customfield_10138
        schema:
          datatype: array
          items: user
      - name: Parent Link
        key: customfield_10018
        schema:
          datatype: any
      - name: Steps to Reproduce
        key: customfield_10777
        schema:
          datatype: string
      - name: Satisfaction
        key: customfield_10139
        schema:
          datatype: sd-feedback
      - name: Project
        key: customfield_10657
        schema:
          datatype: atlas-project
      - name: Approvers (migrated)
        key: customfield_10778
        schema:
          datatype: array
          items: user
      - name: Rank
        key: customfield_10019
        schema:
          datatype: any
      - name: Change risk (migrated)
        key: customfield_10779
        schema:
          datatype: option
      - name: Value
        key: customfield_10130
        schema:
          datatype: number
      - name: Effort
        key: customfield_10131
        schema:
          datatype: number
      - name: Request Type
        key: customfield_10010
        schema:
          datatype: sd-customerrequesttype
      - name: Idea short description
        key: customfield_10132
        schema:
          datatype: string
      - name: Project target
        key: customfield_10374
        schema:
          datatype: string
      - name: Confidence
        key: customfield_10133
        schema:
          datatype: number
      - name: Epic Status
        key: customfield_10012
        schema:
          datatype: option
      - name: Roadmap
        key: customfield_10375
        schema:
          datatype: option
      - name: Effort
        key: customfield_10376
        schema:
          datatype: number
      - name: Epic Color
        key: customfield_10013
        schema:
          datatype: string
      - name: Change type (migrated)
        key: customfield_10772
        schema:
          datatype: option
      - name: Documents
        key: customfield_10134
        schema:
          datatype: string
      - name: Score
        key: customfield_10377
        schema:
          datatype: number
      - name: "[CHART] Date of First Response (migrated)"
        key: customfield_10773
        schema:
          datatype: datetime
      - name: Product Area
        key: customfield_10135
        schema:
          datatype: array
          items: option
      - name: Start date
        key: customfield_10015
        schema:
          datatype: date
      - name: Expected Behaviour
        key: customfield_10774
        schema:
          datatype: string
      - name: Idea short description
        key: customfield_10378
        schema:
          datatype: string
      - name: Work category
        key: customfield_10136
        schema:
          datatype: string
      - name: Change type
        key: customfield_10005
        schema:
          datatype: option
      - name: Designs ready
        key: customfield_10126
        schema:
          datatype: number
      - name: Change risk
        key: customfield_10006
        schema:
          datatype: option
      - name: Project start
        key: customfield_10127
        schema:
          datatype: string
      - name: Change reason
        key: customfield_10007
        schema:
          datatype: option
      - name: Project target
        key: customfield_10128
        schema:
          datatype: string
      - name: Actual start
        key: customfield_10008
        schema:
          datatype: datetime
      - name: Category
        key: customfield_10129
        schema:
          datatype: option
      - name: Actual end
        key: customfield_10009
        schema:
          datatype: datetime
      - name: Impact
        key: customfield_10120
        schema:
          datatype: number
      - name: Impact Score
        key: customfield_10483
        schema:
          datatype: number
      - name: Development
        key: customfield_10000
        schema:
          datatype: any
      - name: Theme
        key: customfield_10121
        schema:
          datatype: array
          items: option
      - name: Focus Areas
        key: customfield_10242
        schema:
          datatype: array
          items: Focus Areas
      - name: Roadmap
        key: customfield_10122
        schema:
          datatype: option
      - name: Team
        key: customfield_10001
        schema:
          datatype: team
      - name: Impact score
        key: customfield_10123
        schema:
          datatype: number
      - name: Organizations
        key: customfield_10002
        schema:
          datatype: array
          items: sd-customerorganization
      - name: Customer segments
        key: customfield_10124
        schema:
          datatype: array
          items: option
      - name: Approvers
        key: customfield_10003
        schema:
          datatype: array
          items: user
      - name: Impact
        key: customfield_10004
        schema:
          datatype: option
      - name: Spec ready
        key: customfield_10125
        schema:
          datatype: number
      - name: Insights
        key: customfield_10115
        schema:
          datatype: number
      - name: Comments
        key: customfield_10116
        schema:
          datatype: number
      - name: Linked items
        key: customfield_10117
        schema:
          datatype: number
      - name: Delivery progress
        key: customfield_10118
        schema:
          datatype: string
      - name: Delivery status
        key: customfield_10119
        schema:
          datatype: string
      - name: Data Sources
        key: customfield_10516
        schema:
          datatype: string
      - name: Key Metrics
        key: customfield_10517
        schema:
          datatype: string
      - name: Requestor's Name/Position
        key: customfield_10518
        schema:
          datatype: string
  types:
    - id: "10000"
      name: Epic
      handle: Epic
      subtask: false
    - id: "10004"
      name: Story
      handle: Story
      subtask: false
    - id: "10005"
      name: Task
      handle: Task
      subtask: false
    - id: "10007"
      name: Bug
      handle: Bug
      subtask: false
    - id: "10526"
      name: Feature Request
      handle: Feature Request
      subtask: false
    - id: "10525"
      name: Design
      handle: Design
      subtask: false
    - id: "10524"
      name: Design QA
      handle: Design QA
      subtask: false
    - id: "10529"
      name: Developer escalation
      handle: Developer escalation
      subtask: false
    - id: "10527"
      name: New Feature
      handle: New Feature
      subtask: false
    - id: "10528"
      name: Support
      handle: Support
      subtask: false
login: {{ JIRA_EMAIL }}
project:
  key: FUL
  type: classic
server: {{ JIRA_HOST }}
timezone: Asia/Dhaka
