banner = true
symlink = false

[packages.d_carapace]
src = "dotfiles/d_carapace"
dest = "~/.config/carapace"
pre_actions = ["{{ PACKAGE_INSTALLER }} carapace"]

[packages.d_carapace.targets]
mac = "~/Library/Application Support/carapace"

[packages.d_yazi]
src = "dotfiles/d_yazi"
dest = "~/.config/yazi/"
dependencies = []
pre_actions = ["{{ PACKAGE_INSTALLER }} yazi"]

[packages.d_jira]
src = "dotfiles/d_jira"
dest = "~/.config/.jira/"
dependencies = []
pre_actions = ["{{ PACKAGE_INSTALLER }} jira-cli"]

[packages.d_jira.prompts]
JIRA_API_TOKEN = "JIRA API TOKEN"
JIRA_EMAIL = "JIRA EMAIL"
JIRA_HOST = "JIRA HOST"

[packages.d_zellij]
src = "dotfiles/d_zellij"
dest = "~/.config/zellij/"
dependencies = []
pre_actions = ["{{ PACKAGE_INSTALLER }} zellij"]

[packages.f_zshrc]
src = "dotfiles/f_zshrc"
dest = "~/.zshrc"
dependencies = []

[packages.f_zshrc.targets]
mac = "~/.zshrc"

[packages.d_bin]
src = "dotfiles/d_bin"
dest = "~/bin"
dependencies = []

[packages.d_bin.targets]
mac = "~/bin"

[packages.d_nvim]
src = "dotfiles/d_nvim"
dest = "~/.config/nvim/"
dependencies = []
pre_actions = ["{{ PACKAGE_INSTALLER }} neovim"]
ignore = [".gitignore", ".git", ".git/**"]

[packages.d_aerospace]
src = "dotfiles/d_aerospace"
dest = "~/.config/aerospace/"
dependencies = []

[packages.d_atuin]
src = "dotfiles/d_atuin"
dest = "~/.config/atuin/"
dependencies = []
pre_actions = ["{{ PACKAGE_INSTALLER }} atuin"]

[packages.d_nushell]
src = "dotfiles/d_nushell"
dest = "~/.config/nushell"
dependencies = ["d_atuin", "d_carapace"]
pre_actions = ["{{ PACKAGE_INSTALLER }} nu direnv zoxide", "cargo install prmt"]
ignore = ["history.txt"]

[packages.d_nushell.targets]
mac = "~/Library/Application Support/nushell"

[packages.d_ghostty]
src = "dotfiles/d_ghostty"
dest = "~/.config/ghostty/"
dependencies = ["d_nushell", "d_zellij"]
pre_actions = ["{{ PACKAGE_INSTALLER }} --cask font-maple-mono"]

[packages.f_gitconfig]
src = "dotfiles/f_gitconfig"
dest = "~/.gitconfig"
dependencies = []
pre_actions = ["{{ PACKAGE_INSTALLER }} git git-delta"]

[packages.f_ssh_config]
src = "dotfiles/f_ssh_config"
dest = "~/.ssh/config"
dependencies = []

[profiles.mac]
dependencies = [
  "d_zellij",
  "d_nvim",
  "d_aerospace",
  "f_gitconfig",
  "d_ghostty",
  "d_atuin",
  "d_jira",
  "f_ssh_config",
  "d_yazi",
  "f_zshrc",
  "d_bin",
  "d_nushell",
  "d_carapace",
]

[profiles.mac.variables]
PACKAGE_INSTALLER = "brew install"

[profiles.default]
dependencies = []
