config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  impignore:
  - '*/known_hosts*'
actions:
  pre:
    install_pkg: '{{@@ pkg_installer @@}} {0}'
    clone_or_update_nu_scripts: mkdir -p ~/.nu/contrib; bash -c "git -C ~/.nu/contrib/nu_scripts
      pull || git clone https://github.com/nushell/nu_scripts.git ~/.nu/contrib/nu_scripts"
    clone_or_update_tpm: mkdir -p ~/.tmux/plugins; bash -c "git -C ~/.tmux/plugins/tpm
      pull || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm"
    clone_or_update_catppuccin_tmux: mkdir -p ~/.tmux/plugins; bash -c "git -C ~/.tmux/plugins/catppuccin
      pull || git clone https://github.com/catppuccin/tmux.git ~/.tmux/plugins/catppuccin"
  post:
    brew_restore: brew tap homebrew/bundle; brew bundle --file=~/Brewfile
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    actions:
    - install_pkg "git git-delta"
  f_gitconfig-official:
    src: gitconfig-official
    dst: ~/.gitconfig-official
  f_gitconfig-personal:
    src: gitconfig-personal
    dst: ~/.gitconfig-personal
  f_nu_env.nu:
    src: Library/Application Support/nushell/env.nu
    dst: ~/Library/Application Support/nushell/env.nu
    actions:
    - install_pkg "nu"
  f_nu_config.nu:
    src: Library/Application Support/nushell/config.nu
    dst: ~/Library/Application Support/nushell/config.nu
    actions:
    - clone_or_update_nu_scripts
  f_starship_init.nu:
    src: cache/starship/init.nu
    dst: ~/.cache/starship/init.nu
    actions:
    - install_pkg "starship"
  f_atuin_init.nu:
    src: local/share/atuin/init.nu
    dst: ~/.local/share/atuin/init.nu
    actions:
    - install_pkg "atuin"
  d_ssh:
    src: ssh
    dst: ~/.ssh
    chmod: preserve
    upignore:
    - '*/known_hosts*'
    - '*/.gitignore'
    - '*/.git*'
    cmpignore:
    - '*/known_hosts*'
    - '*/.gitignore'
    - '*/.git*'
    instignore:
    - '*/known_hosts*'
    - '*/.gitignore'
    - '*/.git*'
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
    - install_pkg "neovim go gh delve"
    upignore:
    - '*/.gitignore'
    - '*/.git*'
    cmpignore:
    - '*/.gitignore'
    - '*/.git*'
    instignore:
    - '*/.gitignore'
    - '*/.git*'
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    actions:
    - install_pkg "tmux"
    - clone_or_update_tpm
    - clone_or_update_catppuccin_tmux
  d_fonts:
    src: Library/Fonts
    dst: '{{@@ font_dir @@}}'
    chmod: '744'
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
    actions:
    - install_pkg "alacritty"
  d_aerospace:
    src: config/aerospace
    dst: ~/.config/aerospace
    actions:
    - install_pkg "--cask nikitabobko/tap/aerospace"
  d_yazi:
    src: config/yazi
    dst: ~/.config/yazi
    actions:
    - install_pkg "yazi"
  f_zoxide.nu:
    src: zoxide.nu
    dst: ~/.zoxide.nu
    actions:
    - install_pkg "zoxide fzf"
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
profiles:
  mac:
    variables:
      font_dir: ~/Library/Fonts
      pkg_installer: brew install
    dotfiles:
    - f_gitconfig
    - f_gitconfig-official
    - f_gitconfig-personal
    - f_nu_env.nu
    - f_nu_config.nu
    - f_starship_init.nu
    - f_atuin_init.nu
    - d_ssh
    - d_nvim
    - f_tmux.conf
    - d_fonts
    - d_alacritty
    - d_aerospace
    - d_yazi
    - f_zoxide.nu
    - f_starship.toml
