config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  import_variables:
  - uservariables.yaml:optional
  impignore:
  - '*/known_hosts*'
uservariables:
  jira_token: Your JIRA API Token
actions:
  pre:
    install_pkg: '{{@@ pkg_installer @@}} {0}'
    install_npm_global: npm install -g {0}
    clone_or_update_nu_scripts: mkdir -p ~/.nu/contrib; bash -c "git -C ~/.nu/contrib/nu_scripts
      pull || git clone https://github.com/nushell/nu_scripts.git ~/.nu/contrib/nu_scripts"
  post:
    brew_restore: brew tap homebrew/bundle; brew bundle --file=~/Brewfile
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    actions:
    - install_pkg "git git-delta"
  f_nu_env.nu:
    src: Library/Application Support/nushell/env.nu
    dst: ~/Library/Application Support/nushell/env.nu
    actions:
    - install_pkg "nu"
  f_nu_config.nu:
    src: Library/Application Support/nushell/config.nu
    dst: ~/Library/Application Support/nushell/config.nu
    actions:
    - clone_or_update_nu_scripts
  f_starship_init.nu:
    src: cache/starship/init.nu
    dst: ~/.cache/starship/init.nu
    actions:
    - install_pkg "starship"
  f_atuin_init.nu:
    src: local/share/atuin/init.nu
    dst: ~/.local/share/atuin/init.nu
    actions:
    - install_pkg "atuin"
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    actions:
    - install_pkg "neovim go gh fnm npm"
    - install_npm_global "@github/copilot"
    upignore:
    - '*/.gitignore'
    - '*/.git*'
    cmpignore:
    - '*/.gitignore'
    - '*/.git*'
    instignore:
    - '*/.gitignore'
    - '*/.git*'
  d_aerospace:
    src: config/aerospace
    dst: ~/.config/aerospace
    actions:
    - install_pkg "--cask nikitabobko/tap/aerospace"
  d_yazi:
    src: config/yazi
    dst: ~/.config/yazi
    actions:
    - install_pkg "yazi"
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_zellij:
    src: config/zellij
    dst: ~/.config/zellij
    upignore:
    - '*'
    actions:
    - install_pkg "zellij"
  d_ghostty:
    src: config/ghostty
    dst: ~/.config/ghostty
    actions:
    - install_pkg "ghostty"
    - install_pkg "--cask font-maple-mono"
  d_atuin:
    src: config/atuin
    dst: ~/.config/atuin
    actions:
    - install_pkg "atuin"
    chmod: '700'
  d_jira:
    actions:
    - install_pkg "jira-cli"
    src: config/.jira
    dst: ~/.config/.jira
    chmod: '700'
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
profiles:
  mac:
    variables:
      pkg_installer: brew install
    dotfiles:
    - f_gitconfig
    - f_nu_env.nu
    - f_nu_config.nu
    - f_starship_init.nu
    - f_atuin_init.nu
    - d_nvim
    - d_aerospace
    - d_yazi
    - f_starship.toml
    - d_zellij
    - d_ghostty
    - d_atuin
    - d_jira
    - f_ssh_config
