[manager]
sort_sensitive = true
sort_dir_first = true
linemode = "size_and_mtime"

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "unix" },
  { run = "nvim %*",   block = true, for = "windows" },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
  { run = '"C:\Program Files\mpv.exe" %*', orphan = true, for = "windows" }
]
