import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

shell = "/opt/homebrew/bin/tmux"

[font]
size = 12.0
normal = { family = "Maple Mono NF", style = "Regular" }
builtin_box_drawing = true

[window]
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"

[env]
TERM = "xterm-256color"
