
[font]
size = 12.0
normal = { family = "Maple Mono NF", style = "Regular" }
builtin_box_drawing = true

[window]
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"
decorations = "None"
padding = { x = 3, y = 3}
dynamic_padding = true

[env]
TERM = "xterm-256color"

[general]
import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[terminal]

shell = "/opt/homebrew/bin/tmux"
